### ISSUE TITLE
Something wrong with ssl

### ISSUE THREAD

**Issue by zcanfly** [srplab/starcore_for_android#1]
When I run my python with urllib to visit the `https` ,it get error.The python file is work well in macOS and windows.

I was call a function like this:
```
def testurl(url):
    print('testurl___')
    context = ssl._create_unverified_context()
    req = request.Request(url)
    _CHROME_USER_AGENT = 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.97 Safari/537.36'
    req.add_header('User-Agent',_CHROME_USER_AGENT)
    with request.urlopen(req,context) as f:
        html = f.read().decode('utf-8')
        print(html)

```
and the error in android like this:
```
12-28 14:46:45.822 7708-7872/com.example.huangchp.myapplication I/<string>,17: testurl___
12-28 14:46:46.784 7708-7872/com.example.huangchp.myapplication I//data/user/0/com.example.huangchp.myapplication/files/p/python3: Traceback (most recent call last):
12-28 14:46:46.785 7708-7872/com.example.huangchp.myapplication I//data/user/0/com.example.huangchp.myapplication/files/p/python3:   File "/data/user/0/com.example.huangchp.myapplication/files/p/python3.5.zip/urllib/request.py", line 1254, in do_open
12-28 14:46:46.785 7708-7872/com.example.huangchp.myapplication I//data/user/0/com.example.huangchp.myapplication/files/p/python3:     h.request(req.get_method(), req.selector, req.data, headers)
12-28 14:46:46.785 7708-7872/com.example.huangchp.myapplication I//data/user/0/com.example.huangchp.myapplication/files/p/python3:   File "/data/user/0/com.example.huangchp.myapplication/files/p/python3.5.zip/http/client.py", line 1107, in request
12-28 14:46:46.785 7708-7872/com.example.huangchp.myapplication I//data/user/0/com.example.huangchp.myapplication/files/p/python3:     self._send_request(method, url, body, headers)
12-28 14:46:46.786 7708-7872/com.example.huangchp.myapplication I//data/user/0/com.example.huangchp.myapplication/files/p/python3:   File "/data/user/0/com.example.huangchp.myapplication/files/p/python3.5.zip/http/client.py", line 1152, in _send_request
12-28 14:46:46.786 7708-7872/com.example.huangchp.myapplication I//data/user/0/com.example.huangchp.myapplication/files/p/python3:     self.endheaders(body)
12-28 14:46:46.786 7708-7872/com.example.huangchp.myapplication I//data/user/0/com.example.huangchp.myapplication/files/p/python3:   File "/data/user/0/com.example.huangchp.myapplication/files/p/python3.5.zip/http/client.py", line 1103, in endheaders
12-28 14:46:46.786 7708-7872/com.example.huangchp.myapplication I//data/user/0/com.example.huangchp.myapplication/files/p/python3:     self._send_output(message_body)
12-28 14:46:46.786 7708-7872/com.example.huangchp.myapplication I//data/user/0/com.example.huangchp.myapplication/files/p/python3:   File "/data/user/0/com.example.huangchp.myapplication/files/p/python3.5.zip/http/client.py", line 934, in _send_output
12-28 14:46:46.786 7708-7872/com.example.huangchp.myapplication I//data/user/0/com.example.huangchp.myapplication/files/p/python3:     self.send(msg)
12-28 14:46:46.786 7708-7872/com.example.huangchp.myapplication I//data/user/0/com.example.huangchp.myapplication/files/p/python3:   File "/data/user/0/com.example.huangchp.myapplication/files/p/python3.5.zip/http/client.py", line 877, in send
12-28 14:46:46.787 7708-7872/com.example.huangchp.myapplication I//data/user/0/com.example.huangchp.myapplication/files/p/python3:     self.connect()
12-28 14:46:46.787 7708-7872/com.example.huangchp.myapplication I//data/user/0/com.example.huangchp.myapplication/files/p/python3:   File "/data/user/0/com.example.huangchp.myapplication/files/p/python3.5.zip/http/client.py", line 1261, in connect
12-28 14:46:46.787 7708-7872/com.example.huangchp.myapplication I//data/user/0/com.example.huangchp.myapplication/files/p/python3:     server_hostname=server_hostname)
12-28 14:46:46.787 7708-7872/com.example.huangchp.myapplication I//data/user/0/com.example.huangchp.myapplication/files/p/python3:   File "/data/user/0/com.example.huangchp.myapplication/files/p/python3.5.zip/ssl.py", line 385, in wrap_socket
12-28 14:46:46.787 7708-7872/com.example.huangchp.myapplication I//data/user/0/com.example.huangchp.myapplication/files/p/python3:     _context=self)
12-28 14:46:46.787 7708-7872/com.example.huangchp.myapplication I//data/user/0/com.example.huangchp.myapplication/files/p/python3:   File "/data/user/0/com.example.huangchp.myapplication/files/p/python3.5.zip/ssl.py", line 760, in __init__
12-28 14:46:46.787 7708-7872/com.example.huangchp.myapplication I//data/user/0/com.example.huangchp.myapplication/files/p/python3:     self.do_handshake()
12-28 14:46:46.788 7708-7872/com.example.huangchp.myapplication I//data/user/0/com.example.huangchp.myapplication/files/p/python3:   File "/data/user/0/com.example.huangchp.myapplication/files/p/python3.5.zip/ssl.py", line 996, in do_handshake
12-28 14:46:46.788 7708-7872/com.example.huangchp.myapplication I//data/user/0/com.example.huangchp.myapplication/files/p/python3:     self._sslobj.do_handshake()
12-28 14:46:46.788 7708-7872/com.example.huangchp.myapplication I//data/user/0/com.example.huangchp.myapplication/files/p/python3:   File "/data/user/0/com.example.huangchp.myapplication/files/p/python3.5.zip/ssl.py", line 641, in do_handshake
12-28 14:46:46.788 7708-7872/com.example.huangchp.myapplication I//data/user/0/com.example.huangchp.myapplication/files/p/python3:     self._sslobj.do_handshake()
12-28 14:46:46.788 7708-7872/com.example.huangchp.myapplication I//data/user/0/com.example.huangchp.myapplication/files/p/python3: ssl.SSLError: [SSL: BAD_SIGNATURE] bad signature (_ssl.c:719)
12-28 14:46:46.789 7708-7872/com.example.huangchp.myapplication I//data/user/0/com.example.huangchp.myapplication/files/p/python3: During handling of the above exception, another exception occurred:
12-28 14:46:46.789 7708-7872/com.example.huangchp.myapplication I//data/user/0/com.example.huangchp.myapplication/files/p/python3: Traceback (most recent call last):
12-28 14:46:46.789 7708-7872/com.example.huangchp.myapplication I//data/user/0/com.example.huangchp.myapplication/files/p/python3:   File "<string>", line 27, in main_func
12-28 14:46:46.790 7708-7872/com.example.huangchp.myapplication I//data/user/0/com.example.huangchp.myapplication/files/p/python3:   File "<string>", line 22, in testurl
12-28 14:46:46.790 7708-7872/com.example.huangchp.myapplication I//data/user/0/com.example.huangchp.myapplication/files/p/python3:   File "/data/user/0/com.example.huangchp.myapplication/files/p/python3.5.zip/urllib/request.py", line 163, in urlopen
12-28 14:46:46.790 7708-7872/com.example.huangchp.myapplication I//data/user/0/com.example.huangchp.myapplication/files/p/python3:     return opener.open(url, data, timeout)
12-28 14:46:46.790 7708-7872/com.example.huangchp.myapplication I//data/user/0/com.example.huangchp.myapplication/files/p/python3:   File "/data/user/0/com.example.huangchp.myapplication/files/p/python3.5.zip/urllib/request.py", line 466, in open
12-28 14:46:46.790 7708-7872/com.example.huangchp.myapplication I//data/user/0/com.example.huangchp.myapplication/files/p/python3:     response = self._open(req, data)
12-28 14:46:46.790 7708-7872/com.example.huangchp.myapplication I//data/user/0/com.example.huangchp.myapplication/files/p/python3:   File "/data/user/0/com.example.huangchp.myapplication/files/p/python3.5.zip/urllib/request.py", line 484, in _open
12-28 14:46:46.790 7708-7872/com.example.huangchp.myapplication I//data/user/0/com.example.huangchp.myapplication/files/p/python3:     '_open', req)
12-28 14:46:46.791 7708-7872/com.example.huangchp.myapplication I//data/user/0/com.example.huangchp.myapplication/files/p/python3:   File "/data/user/0/com.example.huangchp.myapplication/files/p/python3.5.zip/urllib/request.py", line 444, in _call_chain
12-28 14:46:46.791 7708-7872/com.example.huangchp.myapplication I//data/user/0/com.example.huangchp.myapplication/files/p/python3:     result = func(*args)
12-28 14:46:46.791 7708-7872/com.example.huangchp.myapplication I//data/user/0/com.example.huangchp.myapplication/files/p/python3:   File "/data/user/0/com.example.huangchp.myapplication/files/p/python3.5.zip/urllib/request.py", line 1297, in https_open
12-28 14:46:46.791 7708-7872/com.example.huangchp.myapplication I//data/user/0/com.example.huangchp.myapplication/files/p/python3:     context=self._context, check_hostname=self._check_hostname)
12-28 14:46:46.791 7708-7872/com.example.huangchp.myapplication I//data/user/0/com.example.huangchp.myapplication/files/p/python3:   File "/data/user/0/com.example.huangchp.myapplication/files/p/python3.5.zip/urllib/request.py", line 1256, in do_open
12-28 14:46:46.791 7708-7872/com.example.huangchp.myapplication I//data/user/0/com.example.huangchp.myapplication/files/p/python3:     raise URLError(err)
12-28 14:46:46.792 7708-7872/com.example.huangchp.myapplication I//data/user/0/com.example.huangchp.myapplication/files/p/python3: urllib.error.URLError: <urlopen error [SSL: BAD_SIGNATURE] bad signature (_ssl.c:719)>
12-28 14:46:46.793 7708-7872/com.example.huangchp.myapplication W/,27: URLError(SSLError(1, '[SSL: BAD_SIGNATURE] bad signature (_ssl.c:719)'),)
12-28 14:46:46.795 7708-7872/com.example.huangchp.myapplication E/AndroidRuntime: FATAL EXCEPTION: AsyncTask #1
                                                                                  Process: com.example.huangchp.myapplication, PID: 7708
                                                                                  java.lang.NullPointerException: println needs a message
                                                                                      at android.util.Log.println_native(Native Method)
                                                                                      at android.util.Log.i(Log.java:160)
                                                                                      at com.example.huangchp.myapplication.MainActivity.loadPy(MainActivity.java:127)
                                                                                      at com.example.huangchp.myapplication.MainActivity$1.run(MainActivity.java:42)
                                                                                      at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:234)
                                                                                      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                                                      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                                                      at java.lang.Thread.run(Thread.java:818)

```

**Comment by srplab** [comment]
please try with

 with request.urlopen(req,context=context) as f:

**Comment by zcanfly** [comment]
@srplab I try with your solution,but it doesn't work.the error info not change than before.The python file can work well in macOS and windows with `python3.5.4`,but can not work with `starcore_for_android`.

**Comment by srplab** [comment]
please try，

Edit ssl.py, add two lines at function "_create_unverified_context"

    context = SSLContext(protocol)
    # SSLv2 considered harmful.
    context.options |= OP_NO_SSLv2
    # SSLv3 has problematic security and is only required for really old
    # clients such as IE6 on Windows XP
    context.options |= OP_NO_SSLv3
    
    context.options |= OP_NO_TLSv1_1
    context.options |= OP_NO_TLSv1_2

Add ssl.py to assets folder of the project, and then copy it to "/data/data/"+getPackageName()+"/files"

Make sure "/data/data/"+getPackageName()+"/files" is the first folder of python sys.path.

**Comment by zcanfly** [comment]
@srplab ,thank you! It can be work.
ps:[srplab's blog](http://blog.csdn.net/srplab1)is your blog?

**Comment by srplab** [comment]
yes
