### ISSUE TITLE
 java.lang.UnsatisfiedLinkError: Bad JNI version returned from JNI_OnLoad in  libstar_java.so

### ISSUE THREAD

**Issue by Sanjay-F** [srplab/starcore_for_android#7]
version :3.7.3

```
E/AndroidRuntime: FATAL EXCEPTION: A-DelayTaskThread
    Process: com.demo.android, PID: 17617
    java.lang.ExceptionInInitializerError
        at com.srplab.www.starcore.StarCoreFactory.<clinit>(SourceFile:150)
        at com.srplab.www.starcore.StarCoreFactory.a(SourceFile:244)
        at com.demo.android.eventcheck.c.d(SourceFile:313)
        at com.demo.android.eventcheck.c.a(SourceFile:111) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:929)
        at java.lang.Thread.run(Thread.java:929)
     Caused by: java.lang.UnsatisfiedLinkError: Bad JNI version returned from JNI_OnLoad in "/data/app/com.demo.app-sVLVqF3r-DuvdwdY8sAv5g==/lib/arm/libstar_java.so": 0
        at java.lang.Runtime.load0(Runtime.java:938)
        at java.lang.System.load(System.java:1632)
        at com.srplab.www.starcore.StarCoreFactory.<clinit>(SourceFile:146)
        at com.srplab.www.starcore.StarCoreFactory.a(SourceFile:244) 
        at com.demo.android.eventcheck.c.d(SourceFile:313) 
        at com.demo.android.eventcheck.c.a(SourceFile:111)
```

**Comment by srplab** [comment]
please change targetSdkVersion < 29 of the project. The problem will be solved at next release

**Comment by Sanjay-F** [comment]
> please change targetSdkVersion < 29 of the project. The problem will be solved at next release

When will the next version be released?
